name = "DN3"
uuid = "3dbf8b18-b0ef-4f17-9b3f-30222f361ead"
authors = ["MATEJ-VICTUS\\klanc <klancar.matej@gmail.com>"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
